module uart_interface #(
    parameter integer CLK_FREQ = 27_000_000,
    parameter integer BAUD_RATE = 9_600,
    parameter integer DATA_BITS = 8,
    parameter integer OVERSAMPLE_RATE = 16
)(
    input  wire                    i_clk,
    input  wire                    i_reset,
    
    input  wire                    i_rx,         // UART physical input
    input  wire                    i_rd_uart,    // Read request from the system
    input  wire                    i_wr_uart,    // Write request from the system
    input  wire [DATA_BITS-1:0]    i_write_data, // Data provided by the system for transmission.

    output wire                    o_tx,        // UART physical output
    output wire                    o_rx_empty,  // High when there is no unread received byte.
    output wire                    o_tx_busy,   // High while the transmitter is busy.
    output wire [DATA_BITS-1:0]    o_read_data  // Most recently received data.
);

    // Internal UART signals
    wire                 baud_tick; // Timing pulse generated by the baud generator.
    wire                 rx_done;   // Pulses when a complete byte has been received.
    wire                 tx_done;   // Pulses when a complete byte has been transmitted.
    wire [DATA_BITS-1:0] rx_data;   // Data received by the UART receiver.

    // Interface registers
    reg [DATA_BITS-1:0] read_data_reg; // Holds the received data until it is read.
    reg                 rx_empty_reg;  // Indicates whether the receive register contains unread data.
    reg                 tx_busy_reg;   // Indicates whether the transmitter is currently busy.


    // Baud rate generator
    baud_rate_generator #(
        .CLK_FREQ        (CLK_FREQ),
        .BAUD_RATE       (BAUD_RATE),
        .OVERSAMPLE_RATE (OVERSAMPLE_RATE)
    ) baud_gen_unit (
        .i_clk   (i_clk),
        .i_reset (i_reset),
        .o_tick  (baud_tick)
    );

    // UART receiver
    uart_rx #(
        .DATA_BITS       (DATA_BITS),
        .OVERSAMPLE_RATE (OVERSAMPLE_RATE)
    ) rx_unit (
        .i_clk       (i_clk),
        .i_reset     (i_reset),
        .i_rx        (i_rx),
        .i_baud_tick (baud_tick),
        .o_rx_done   (rx_done),
        .o_data_out  (rx_data)
    );

    // UART transmitter
    uart_tx #(
        .DATA_BITS       (DATA_BITS),
        .OVERSAMPLE_RATE (OVERSAMPLE_RATE)
    ) tx_unit (
        .i_clk       (i_clk),
        .i_reset     (i_reset),
        .i_tx_start  (i_wr_uart && !tx_busy_reg),
        .i_baud_tick (baud_tick),
        .i_data_in   (i_write_data),
        .o_tx_done   (tx_done),
        .o_tx        (o_tx)
    );

    // Interface and buffer management
    always @(posedge i_clk) begin

        if (i_reset) begin

            rx_empty_reg <= 1'b1; // Receive interface starts empty.
            tx_busy_reg <= 1'b0;  // Transmitter starts available.
            read_data_reg <= 0;   // Clear stored receive data.

        end
        else begin

            //----------------------------------------------------
            // Receive interface
            //----------------------------------------------------
            // A complete byte has been received.
            if (rx_done) begin
                read_data_reg <= rx_data; // Store the received data.
                rx_empty_reg <= 1'b0;     // Mark the receive register as containing data.
            end
            // The system has read the received data.
            else if (i_rd_uart) begin
                rx_empty_reg <= 1'b1; // Mark the receive register as empty.
            end


            //----------------------------------------------------
            // Transmit interface
            //----------------------------------------------------
            // The system requested a transmission and the transmitter was available.
            if (i_wr_uart && !tx_busy_reg) begin
                tx_busy_reg <= 1'b1; // Mark the transmitter as busy.
            end
            // The complete byte has finished transmitting.
            else if (tx_done) begin
                tx_busy_reg <= 1'b0; // Mark the transmitter as available.
            end

        end
    end

    // Interface outputs
    assign o_read_data = read_data_reg;
    assign o_rx_empty  = rx_empty_reg;
    assign o_tx_busy   = tx_busy_reg;

endmodule
